### PR TITLE
Improved Start View Scene to support multiple screen aspect ratio

### LINKED ISSUE #355: Start View Scene does not support multiple screen aspect ratio
## Description
As a user,
I need not to see extra blank space on my screen when opening the game for first time, there is a scope of improvement in UI and UX.
Start View is looking perfect on iPhone 8 Plus and below, but not on iPhone X or above.

## Mocks
Screenshot 2020-02-29 at 3 20 13 PM

## Acceptance Criteria

The Start View Scene should look like this on iPhone X and above:
Screenshot 2020-02-29 at 3 08 41 PM

### Update [Required]
- [ ] Check and update image assets where appropriate
- [ ]  Update full screen asses (such as backgrounds) to be aspect ratio agnostic (maybe extra neutral space around the edges)
- [ ]  Update storyboard layouts to use the new visual assets
  
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by vatsalkul**
### Description
Start View Scene now support multiple screen aspect ratio i.e. iPhone X and above. Edited background image and add new image assets like, new game button, about button, load game button.

Fixes [#355 ](https://github.com/anitab-org/powerup-iOS/issues/355)

### Type of Change:

- User Interface
- User Experience

### How Has This Been Tested?
Tested on multiple simulators like iPhone 11 Pro, iPhone 8 Plus, iPhone SE

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by sunjunkie** [comment]
This is a good start but it needs more work. 
1 - you only provide a 1x button images. But it's important to provide 2x and 3x images. The images are now 191 x 996 pixels which is unnecessarily large for their use in the app. Also, while you can put the same image in all 3 spots in the imageasset, it takes more processing to scale the image to the appropriate size at runtime.
2 - Do not position buttons by using proportional height and width. The buttons will be distorted. You have specified the button size to be .1 x the width and .3 x the height. On an iphone 6, this results in an aspect ratio of .58 (height/width). On an iPhone X Max, this results in an aspect ratio of .72. So there will be some image distortion. The aspect ratio should remain the same. It is not necessary to have a larger button on a larger phone.

So, decide on a good size for the button image and create an appropriately-sized png for 2x and 3x. Keep the button size the same for all iPhone sizes, and position the button relative to the safe area or relative to other UI elements.

**Comment by vatsalkul** [comment]
Thank you for such a valuable feedback. I have successfully made changes in my PR.
783 x 150 is the resolution I found good. How I made this decision? I have put the image on an art board in Sketch(designing/prototyping tool) having size same as iPhone 11 Pro Max. Then after getting an appropriate look of image, I exported that it in 1x, 2x, 3x. Hope you will like this approach.
Screenshot 2020-03-03 at 10 08 21 PM

Also, every image asset needs 3 sizes (1x,2x,3x) but actually our image assets are of same resolutions and kept in 1x,2x,3x. I think that all the images need to be proper sizes.

**Comment by sunjunkie** [comment]
I am getting the PRs merged finally. Can you resolve the conflict with this PR and submit a new PR? Thank you.

**Comment by vatsalkul** [comment]
@sunjunkie I have solved the merging conflicts. Please have a look

**Review by sunjunkie — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
