### PR TITLE
Completed View Controller merged into Result View controller

### LINKED ISSUE #282: View Controllers with minor differences should be merged into one
## Description
As a developer,
I want to reduce duplication of view controllers,
so that I can reduce errors resulting from view controllers getting out of sync.

## Mocks
See Results View Controller and Completed View Controller in the storyboard. 

### Update [Required]
- [ ] View Controllers that have only minor differences from each other should be merged.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
The two view controllers (Results View Controller and Completed View Controller) look identical. We should not have 2 identical view controllers. We should just have one in the storyboard.

I will merge the completed view controller to Result View Controller in StoryBoard.
Remove all unused codes of CompletedViewController.

 **This :-**
systrs

**To This:-**
systers11

Fixes #282 

### Type of Change:

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
On simulator.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anubhavpulkit** [comment]
@sunjunkie I Changed Storyboard part but I have some issue in Codebase to completely merged  `Completed View Controller` into `Result View controller`.
I think if you find this storyBoard is fine then I change code in codebase by taking help from yours.

**Comment by anubhavpulkit** [comment]
@sunjunkie can you please have a look because it works fine single change which I did in the first commit.

**Comment by sunjunkie** [comment]
See comments in issue #282

**Comment by anubhavpulkit** [comment]
@sunjunkie Complete in commit 8942022c1a95e7de0f1d25341fe72213be8a7bec Please have a look.

**Review by sunjunkie — APPROVED** [review]

**Pull request merged**
