### PR TITLE
Updated About view Controller

### LINKED ISSUE #243: Modifying AboutView Controller
## Description
As a developer,
I want to change the about screen so that the android and iOS version of app will be consistent..

## Mocks
image

## Acceptance Criteria
When About Screen is made consistent with android.
### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
I think about view is more beautiful and impactful if it looks normal without any complexity, So I send this PR to present the same.

Fixes #243 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)
### How Has This Been Tested?

[about view.mov.zip](https://github.com/anitab-org/powerup-iOS/files/4498847/about.view.mov.zip)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anubhavpulkit** [comment]
All additional changes are complete in this PR.
- [x] Change the 2nd heading to "Why is Powerup needed?"
- [x] Have you looked at Attributed Strings in iOS. You can easily highlight the headings using that.
- [x] The text and Title ("About") is not lined up on the left side.
- [x] When I click the about button, there is a screen flicker before the actual text is shown.

**Comment by anubhavpulkit** [comment]
@sunjunkie Please have a look this PR.

**Comment by sunjunkie** [comment]
This is better. 
- You are not using attributed strings so please remove that item from the checklist.
- The right margin for the text should be moved to the left more - so it is more in line with the current version.
- Why did you put the question strings in the code? Move them into the string constants file.

**Comment by sunjunkie** [comment]
(I accidentally put this comment in the wrong PR! 😟)
-------------------
This looks great. But you reverted the 2nd question - "Why is Powerup needed?" :-)

So while you're at it: you repeat the same UIColor specifications 6 times. It should be in a constant so any changes must done only once. Repeating code like that creates a chance for introducing a bug when making changes. Consider the following instead:

          let aboutColor = UIColor(red: 74/255, green: 160/255, blue: 166/255, alpha: 1.0)

           let attributesHeading: [NSAttributedString.Key : Any] = [
               .foregroundColor: aboutColor,
              .font: UIFont(name: "HelveticaNeue-Bold", size: 24)!
           ]
           let attributesText: [NSAttributedString.Key : Any] = [
              .foregroundColor: aboutColor,
              .font: UIFont(name: "HelveticaNeue", size: 20)!
           ]

           attributedString.addAttributes(attributesHeading, range: NSRange(location: 0, length: 8))
           attributedString.addAttributes(attributesText, range: NSRange(location: 10, length: 578))
           
          ...

**Pull request closed without merging**
