### PR TITLE
Set Deployment target to 10.0

### LINKED ISSUE #288: Drop support for iOS 9
## Description
As a developer,
I want to drop support for iOS 9,
so that I can remove unnecessary code.

## Notes:
As of June 5, 2018, 95% of iOS devices are running iOS 10/11 and iOS 12 is coming out this fall. (iOS tends to have a high rate of upgrade adoption.) iOS 10 is compatible with iPhone 5 and later.

### Update [Required]
- [ ] project supports iOS 10 and above
- [ ] all availability conditions that test for ios version 9 (or 10+) are removed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
set deployment target to 10.0 and removed IOS 9 code

Fixes #288 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anubhavpulkit** [comment]
@mayburgos @SIMRAN1 Have a look?

**Review by sunjunkie — CHANGES_REQUESTED** [review]
The deployment target of the Powerup Target in the project is still set to 9.1 (which will override the project level deployment target.
Also, the "If #available" statements need to be fixed so unnecessary code (for iOS 9 and below) is removed (see StorySequencePlayer.swift).
Please fix these items and resubmit.

**Comment by anubhavpulkit** [comment]
> The deployment target of the Powerup Target in the project is still set to 9.1 (which will override the project level deployment target.
> Also, the "If #available" statements need to be fixed so unnecessary code (for iOS 9 and below) is removed (see StorySequencePlayer.swift).
> Please fix these items and resubmit.

ok

**Comment by anubhavpulkit** [comment]
@sunjunkie Done😀

**Comment by sunjunkie** [comment]
1 - there are actually 2 locations in StorySequencePlayer.swift that test for iOS version. You only fixed one.
2 - You should get rid of any "if #available(iOS 10.0, *)" **test statement** since it is no longer needed. 

I am going to close this issue and replace it with an issue to set the minimum iOS support to iOS 11. (So the issues fixed will be different.)

**Pull request closed without merging**
