### PR TITLE
solving Map Overlap

### PR DESCRIPTION
**Pull request by MANI14011998**
### Description
There's a small error in which the school overlaps the smoke coming out of the house's chimney.

Fixes # [ISSUE]
Map Overlap

### Type of Change:
change the Image With chimney One 
`
Screenshot 2020-02-21 at 10 01 56 PM
`

### CODE REVIEW

**Comment by anubhavpulkit** [comment]
@MANI14011998 I was already working on this issue.

**Comment by sunjunkie** [comment]
@MANI14011998 please read the following guidelines for contributing to the repo. An issue must be approved before you can work on it.
https://github.com/anitab-org/powerup-iOS/wiki/How-to-Contribute

**Comment by MANI14011998** [comment]
Ohhhh pardon @sunjunkie I am opening an issue .  Also I will make sure next time it will never happen again .

**Comment by sunjunkie** [comment]
This issue is part of issue #264. It cannot be solved alone.

**Pull request closed without merging**
