### PR TITLE
iOS new branch

### PR DESCRIPTION
**Pull request by sanyajain**
A fresh branch with all the changes- included libsqlite3.dylib file and FMDB wrapper files

### CODE REVIEW

**Comment by jenpaff** [comment]
Sorry Sanya, I get the same compiler error as before when running your PR. Please double check with Deepika (to reassure that it's not just on my machine) and contact me for a code review. We should aim to get some of your code to work asap

**Comment by sanyajain** [comment]
Hey. I checked the error myself this time. I have rectified the error that is being displayed. Please go the link https://github.com/sanyajain/PowerUp/tree/iOS-new-branch and click on Download Zip and then run the code by clicking on Database.xcodeproj. I did the same and it's building for me. Please try again and let me know if you can do it or not. I have asked Deepika to do the same. Thanks :)

**Comment by jenpaff** [comment]
Hi Sanya, what error was it exactly that you fixed? I still get the same error plus a path error because of the fmbd header file. Please let me know what Deepika says

**Comment by sanyajain** [comment]
Hi Jennifer, did you pull the new commit to your repo or did you follow the procedure that I have mentioned above? I downloaded the zip from the link and then extracted those files on my machine and then ran the project on xcode and it is building for me.. I am not sure if it will work by pulling the new commit or not. For that I will send a new PR so that you can pull the changes in a fresh repo.. I have asked Deepika to do the same and I shall let you know as soon as I hear from her. If we can't work it out after this also, then please let me know when you will be free, we could have a Google Hangout Session sometime that's convenient for you and Deepika. Thanks.

**Comment by jenpaff** [comment]
I tried the PR first and it didn't work and then I followed your
instructions and it didn't work either.
Please keep in mind that sometimes your code could work in your forked
repo, because you made initial changes to your paths, etc., but we have to
make sure that the code works in the original repo, because that's where it
will be merged to.

I'm sorry it's such a hassle, but we have to ensure that everything we
merge works 100%. Please don't be discouraged, especially with your first
pull request. I'm sure once we managed to fix the errors, the rest will go
smoothly :) I will be back in University on Thursday and then I can also
try and run the code on the University computers, but I fear that there are
some general errors in the code since the files can't be found.

Hope that helps.

Jennifer

**Comment by kangaroo5383** [comment]
@sanyajain there are two options I would suggest here:

1. It looks like fmdb is an external library.  There is a dependency manager call Cocoapod that's very easy to use for something like that. you can check how to use it here:  http://cocoapods.org  

2. Alternatively you can fix the path as @jenpaff suggested.
image
image
- select one of the problematic files, make sure that "location" is "Relative to group", then click on the folder icon and navigate to the right location.

I would highly recommend you use the method 1 - it's much easier to manage.

**Comment by kangaroo5383** [comment]
Also the repository doesn't have the proper settings for ignoring files that shouldn't be in the repository.

See comment here:
https://github.com/systers/PowerUp/pull/2#issuecomment-116396810

**Comment by sanyajain** [comment]
@jenpaff I have fixed the paths again for some files as suggested above. Please let me know if you can build it on your machine now or not. I am also working on the first option. If this doesn't work, I will make a new pull request with the first alternative i.e. CocoaPod. 
But if you can, please try building it again with the new commit with path changes and let me know what errors you get, if any.Thanks.

**Comment by jenpaff** [comment]
@sanyajain Great Work! I just tested it on an iOS device and it seems to work. Please make sure you disable all textfields, so that the user can't type in the textfield & then it's all good to merge

**Comment by jenpaff** [comment]
Hey Sanya! Just tested your code again. In your last commit the Database folder isn't accessible therefore it can't be compiled

**Comment by sanyajain** [comment]
Hey! Thanks Jennifer for pointing that out. I think it happened because of the .gitignore file. I have again added the Database folder and now it should work fine. Please do check once and let me know!

**Comment by jenpaff** [comment]
Great work, just two things I noticed: 
- Textfield on Level 1 should be bigger such that the user doesn't have to scroll down to read the whole question
- Textfield on Level 2 / Scene 3 doesn't fit on the screen, so please make sure that works.

Ping me if you have any questions

**Comment by sanyajain** [comment]
I just committed a few changes. In the latest commit, you will find that all scenes in Level 2 have been developed with images and conversations. 
  1. I have made the textfield bigger for the first conversation screen in  Level 1. Please check once and let me know if it's fine.
  2. Level 2 has been changed now. Have a look at the new scenario and let me know if there are any changes.

**Comment by jenpaff** [comment]
Well done, looks great! @rosariorobinson +1 ready to merge!

**Pull request merged**
