### PR TITLE
set deployment target to 10.0 and removed IOS 9 code

### LINKED ISSUE #288: Drop support for iOS 9
## Description
As a developer,
I want to drop support for iOS 9,
so that I can remove unnecessary code.

## Notes:
As of June 5, 2018, 95% of iOS devices are running iOS 10/11 and iOS 12 is coming out this fall. (iOS tends to have a high rate of upgrade adoption.) iOS 10 is compatible with iPhone 5 and later.

### Update [Required]
- [ ] project supports iOS 10 and above
- [ ] all availability conditions that test for ios version 9 (or 10+) are removed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by hashah88**
### Description
Set the "deployment target" to 10.0 from 9.1 and removed checks for IOS 9 availability. 

Fixes #288 288 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by hashah88** [comment]
When I ran the code locally, the app did not crash and it worked .  Also, it worked with IOS 11.4.

**Comment by hashah88** [comment]
Any ideas what might be wrong and how could I solve the issue?

**Comment by sunjunkie** [comment]
The Travis commands is incorrect. I'll fix it.

**Comment by sunjunkie** [comment]
@hashah88 The travis config should be good now. But you also need to update the Deployment Target in the Powerup Project config and in the PowerupTests target. Do that and update this pull request.

**Comment by identity2** [comment]
The travis config is updated to iOS 10 in fa7db91, so this issue could be fixed by:
1. Fetch the latest remote branch to your local repository.
2. Merge it with this branch.
3. Push it to GitHub.
This will rerun the Travis tests with the correct config. (And thus pass the tests.)

**Pull request closed without merging**
