### PR TITLE
Requesting App Ratings

### LINKED ISSUE #334: Requesting App Ratings
## Description
As a user If I want to give a rating this app, I need to go to the app store to give ratings.
I need to displays an in-app prompt that asks for a rating.

With the help of apple official API StoreKit we call the SKStoreReviewController An object that controls the process of requesting App Store ratings and reviews from users.

In which the system offers a consistent, nonintrusive way for apps to request ratings. To use this feature, you simply identify places in your app's user experience where it makes sense to ask for feedback. If the user hasn't already given feedback, the system displays an in-app prompt that asks for a rating. The user can supply feedback or dismiss the prompt with a single tap. 

## Mocks
review1

### Update [Required]
- [displays app prompt that asks for a rating]
- [conforms to Apple's Human Interface Guidelines for requesting ratings and reviews]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
Requesting ratings in Powerup-iOS apps. Starting with iOS 10.3, Apple introduced the new SKStoreReviewController class to standardize this interaction.

Choosing where and when to display this prompt is critical to your success using this API.
The moment the system shows the prompt to the user can have a great effect on the result when requesting app rating that's why I choose 'Sink To Swim' Game up to 'sink to swim' user experience full app to give a rating and when the transition to the game over scene then displays an in-app prompt that asks for a rating.

PR3

**Note: The Submit button will appear grayed out since you are in development mode. It will appear enabled for users using your app through the App Store.**

pr3 1

Fixes #334 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
On Simulator

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by anubhavpulkit** [comment]
@sunjunkie Please have a look.

**Comment by sunjunkie** [comment]
There should be some throttling of the ratings request. Take a look at Apple's guidelines and sample code: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews.

**Comment by anubhavpulkit** [comment]
@sunjunkie The system automatically limits the display of the prompt to three occurrences per app within a 365-day period.
No matter how many times you request the review prompt, the system will show the prompt a maximum of three times in a 365-day period.

The system must not have shown the prompt for a version of the app bundle that matches the current bundle version. This ensures that the user is not asked to review the same version of your app multiple times.

The code sample used to delay the review request only.

**Comment by anubhavpulkit** [comment]
> There should be some throttling of the ratings request. Take a look at Apple's guidelines and sample code: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews.

I read this documentation before sending this PR the sample code used to delay the review request only.

**Comment by anubhavpulkit** [comment]
@sunjunkie Do you want any changes in this Pull Request?

**Comment by sunjunkie** [comment]
The sample code delays the ratings request for a reason. 

Because "the prompt will only be displayed to a user a maximum of three times within a 365-day period", choosing when and where to display this prompt is critical to the success of getting a rating.  "Techniques to delay the call are valuable as they will cause it to be shown to more experienced users that are getting real value from using your app." If you space out the ratings request, you can prompt the user every 10 or 20 times (as an example) they use the app. Doing it 3 times in a row will more likely irritate the user and you could get a worse rating. You get 3 prompts in a year. Use them wisely.
Another thing to consider is to let the user use/launch the app a few times before you request a rating the first time.

Give this some thought and then provide a proposal for when and where to insert ratings requests.

**Comment by anubhavpulkit** [comment]
> The sample code delays the ratings request for a reason.
> 
> Because "the prompt will only be displayed to a user a maximum of three times within a 365-day period", choosing when and where to display this prompt is critical to the success of getting a rating. "Techniques to delay the call are valuable as they will cause it to be shown to more experienced users that are getting real value from using your app." If you space out the ratings request, you can prompt the user every 10 or 20 times (as an example) they use the app. Doing it 3 times in a row will more likely irritate the user and you could get a worse rating. You get 3 prompts in a year. Use them wisely.
> Another thing to consider is to let the user use/launch the app a few times before you request a rating the first time.
> 
> Give this some thought and then provide a proposal for when and where to insert ratings requests.

Ok, Can I take one day to complete this issue because in sample code some errors occur which is Type 'String' has no member errors?

**Comment by anubhavpulkit** [comment]
@sunjunkie How I provide a proposal for when and where to insert rating requests is it in PDF or PPT?

**Comment by sunjunkie** [comment]
Take all the time you need. There is no hurry. You can put your ideas in the comments if it's not too long. Otherwise a pdf is fine.

Since you will be submitting a new PR, it might be better to put this in the issue itself.

**Comment by anubhavpulkit** [comment]
@sunjunkie I complete this PR sorry for the delay. This delay because of my exams going at the same time.

**When and where to insert rating requests.**

I think up to 'sink to swim' game user experience full app to give a rating and when the transition from game to the game complete scene (when we show score) is the best place to displays an in-app prompt that asks for a rating.

And we can't display an in-app prompt that asks for a rating until the user experiences it 4 times and the user is not asked to review the same version of your app multiple times which is apple requirement.

Can I send updated PR?

**Comment by sunjunkie** [comment]
That sounds fine. You can send an updated PR.

**Comment by anubhavpulkit** [comment]
@sunjunkie Done in commit ff218cb097214fd25320ce6bcbc29a163525eef6.

**Review by sunjunkie — APPROVED** [review]
Looks good.

**Comment by anubhavpulkit** [comment]
> Looks good.

Thank You @sunjunkie

**Pull request merged**
