### PR TITLE
Enhancement of AboutViewController 

### PR DESCRIPTION
**Pull request by MANI14011998**
### Description
Enhancement of AboutViewController    

Fixes  [#243 ]

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach

## MockUp

WhatsApp Image 2020-02-25 at 12 59 16 AM
WhatsApp Image 2020-02-25 at 1 04 47 AM

**Code/Quality Assurance Only**

-  My changes generate no new warnings 
- My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- New and existing unit tests pass locally with my changes
- Any dependent changes have been published in downstream modules
- Bug fix (non-breaking change which fixes an issue)
- New feature
- Tested On simulator 

**Code On**

- AboutViewController 
- Added TableView and Extension
- Added collapsed Feature In there
- Created AboutViewController.swift 
- TableViewDeleGate for changing in tableView 
- Created aboutTableViewCell
- edited String.swift

**Get To Know/Personal Achievement**
- String.swift 
- Structure of PowerUp 
- Gets idea about future proposal
- Style Guideline 
- Guidance with mentors

### CODE REVIEW

**Comment by MANI14011998** [comment]
@justKD @sunjunkie  please review and if It need Change Please tell

**Comment by sunjunkie** [comment]
This looks good but the initial view should have all 3 sections collapsed (as you show in your first screenshot above) so that it is immediately obvious that there are 3 sections of information.

**Comment by MANI14011998** [comment]
Ohk sure I will change that with in 10 mins

**Comment by MANI14011998** [comment]
@sunjunkie  please have a look

**Comment by sunjunkie** [comment]
That'a good but I noticed that the text of the 3rd heading does not fit. You'll need to redesign this so that all the heading text fits. (I tested on iphone 8 and 8 plus)

**Comment by MANI14011998** [comment]
Can you send me sreenshot so that I will understand more !

**Comment by sunjunkie** [comment]
Simulator Screen Shot - iPhone 8 Plus - 2020-02-25 at 01 11 48

**Comment by MANI14011998** [comment]
Ohhh got it

**Comment by MANI14011998** [comment]
@sunjunkie ma'am review that

**Review by sunjunkie — APPROVED** [review]

**Comment by sunjunkie** [comment]
@MANI14011998 I've been merging PRs finally. However, there is a conflict now with your PR. Can you resolve this and resubmit? Thanks.

**Comment by sunjunkie** [comment]
@MANI14011998 Can you please resolve the conflicts in this PR? Otherwise, I must make this issue available to someone else.

**Pull request closed without merging**
