### PR TITLE
iOS branch

### PR DESCRIPTION
**Pull request by sanyajain**

### CODE REVIEW

**Comment by jenpaff** [comment]
Just pulled your changes and build fails straight away. Have you tried running your code on the simulator or an iOS device to test it ?

**Comment by sanyajain** [comment]
Yes Jennifer, I did rune the code on the simulator (Hardware- iPhone 6). It was running for me.

**Comment by sanyajain** [comment]
Did you pull all the commits in the order?

**Comment by sanyajain** [comment]
Hey, I just ran the latest commit on my mac and its building for me.What error is displayed while Building the code?

**Comment by sanyajain** [comment]
Hey, I just added the FMDB wrapper files in the project. Please pull the changes and try to build the code again and let me know.

**Comment by rosariorobinson** [comment]
are we still working on this?

**Comment by sanyajain** [comment]
Hey, this is the old branch!! 
the new branch is this: 
https://github.com/systers/PowerUp/pull/4
https://github.com/sanyajain/PowerUp/tree/iOS-new-branch

**Comment by sanyajain** [comment]
Pull request 4 is the one with all the updates, I shall delete this branch.

**Pull request merged**
