### PR TITLE
About View Update

### LINKED ISSUE #243: Modifying AboutView Controller
## Description
As a developer,
I want to change the about screen so that the android and iOS version of app will be consistent..

## Mocks
image

## Acceptance Criteria
When About Screen is made consistent with android.
### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
I think About view is more beautiful and impactful if it looks normal without any complexity, So I send this PR to present the same.

Fixes #243 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)
### How Has This Been Tested?

[about view.mov.zip](https://github.com/anitab-org/powerup-iOS/files/4498847/about.view.mov.zip)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anubhavpulkit** [comment]
@sunjunkie I think is the final one, and you like😀.

**Comment by anubhavpulkit** [comment]
@sunjunkie please have a look new commit 7b98af2998c2193b48fa852fc3ee33e806dc89a4

**Comment by sunjunkie** [comment]
Looks great.

**Comment by anubhavpulkit** [comment]
Then why you close this PR without merge? If is look great Im working on this issue from so many day @sunjunkie ☹️

**Review by sunjunkie — APPROVED** [review]

**Comment by sunjunkie** [comment]
Did not mean to close this without merging!

**Comment by anubhavpulkit** [comment]
Thank You @sunjunkie 😁

**Pull request merged**
