### PR TITLE
Result View Controller background image fix

### LINKED ISSUE #362: Background image of Result view Controller is not cover full screen in iPhone X models
## Description
Background image of the Result view controller is not in full screen because of we use safe-area alignment in Trailing, Leading, Bottom and top of the background image so it does not look as we want.

## Mocks
sys 3848

### Update [Required]
- [x] [update background constraints to Superview]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[30] min

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
Background image Constraints of Result View Controller is changes from safe area to superview so it covers the full screen in every iPhone models.
And because of the last commit of Improved start screen by vatsalkul complete view controller add again so I fix that problem also in this Pull Request.

Fixes #362 

### Type of Change:
**Delete irrelevant options.**

- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
result view

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by anubhavpulkit** [comment]
@sunjunkie Sorry for disturbing you on weekends, please have a look🙃.

**Comment by sunjunkie** [comment]
1 - I am seeing conflicting constraints in your storyboard. (You might want to start again with a fresh copy of the repo.)
2 - Only submit fixes in this PR that refers to the actual issue (Result View Controller background image)

**Comment by anubhavpulkit** [comment]
Ok, @sunjunkie Can we talk about GSoC proposal when you free?

**Comment by anubhavpulkit** [comment]
> 1 - I am seeing conflicting constraints in your storyboard. (You might want to start again with a fresh copy of the repo.)
> 2 - Only submit fixes in this PR that refers to the actual issue (Result View Controller background image)

After clean and build everything is running fine @sunjunkie

**Review by sunjunkie — APPROVED** [review]

**Pull request merged**
