### PR TITLE
Change background image constraints of Avatar View 

### LINKED ISSUE #361: Background image of Avatar view is not cover full screen in iPhone X models.
## Description
Background image of Avatar view controller is not in full screen because of we use safe-area alignment on background also it does not look as we want.

## Mocks
systers issue

### Update [Required]
- [x] [update background constraints ]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
In this Pull Request, I changed the constraint of Avatar View so their Background looks beautiful and stretch on the whole screen.

systers PR

Fixes #361 

### Type of Change:

- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
On simulator

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by sunjunkie** [comment]
I will look at this. Meanwhile, I am going to be more strict about the description template. Please remove the bullet points that do not apply to this PR. E.g., "new feature".

**Comment by anubhavpulkit** [comment]
@sunjunkie Please have a look, is it ok now?

**Comment by sunjunkie** [comment]
Didn't you perform a self review of your own code? 😄

**Comment by anubhavpulkit** [comment]
Ok 🙃

**Comment by sunjunkie** [comment]
Oh, I meant that you forgot to check the checkbox "I have performed a self review...."  in the description above.  😄

**Comment by anubhavpulkit** [comment]
@sunjunkie hahahhah ok from next PR I remember this checkbox😁

**Comment by sunjunkie** [comment]
I'm getting compile errors in AppStoreReviewManager.swift in your PR.

**Comment by anubhavsingh16** [comment]
So can I resend new PR or you resolve this conflict?

**Comment by anubhavpulkit** [comment]
Okk yes I get the same issue because when we clone this repo then UserDefaults+Key.swift is not present in the repo file I don't know why but it is present in Github code

**Comment by anubhavpulkit** [comment]
powerup-iOS/Utilities/UserDefaults+Key.swift file is lost when we clone this repo.

**Comment by sunjunkie** [comment]
I wonder if it has something to do with the fact that you created a Utilities folder (outside the Powerup folder) and the project itself already had a project folder named Utilities (project folder only).

**Comment by anubhavpulkit** [comment]
Yes, you are right I have to put UserDefaults+Key.swift file inside the project folder then it works fine

**Comment by anubhavpulkit** [comment]
I think it works fine in commit a6530cd92f3e1399ef252c0c3aa07cbddc66cae8

**Comment by sunjunkie** [comment]
No, it's not working for me. BTW, you should never move any files around in the Finder or create folders if they are part of an xcode project. Only work within XCode. It's nice to have the Groups mirrored in the Finder but never work on file or folder organization directly in the Finder. 
Also, the AppStoreReviewManager.swift should be in the Powerup folder NOT outside it.
So we still have a project/file issue that needs to be fixed - I will look at it later.

**Comment by anubhavpulkit** [comment]
Ok, so can I leave this one for now?

**Comment by sunjunkie** [comment]
@anubhavsingh16 The file issues are fixed. Please resubmit this PR per the updated repo.

**Comment by anubhavpulkit** [comment]
Hey, @sunjunkie Constraints of Avatar is changed in any Pull Request before. This error is not present now. I don't know how issue solve automatically?

**Comment by anubhavpulkit** [comment]
So Can I close this Pull Request?

**Pull request closed without merging**
