### PR TITLE
add safe area for continue button

### LINKED ISSUE #327: Continue button is running out of screen in iPhone 11 Pro Max
## Description
To Continue the game, Continue button is used which is not at a proper place. Some part of the Continue button is out of the screen when we open in iPhone 11 Pro Max Simulator in Orientation Landscape Right.  

## Mocks
[
systers
 ]

### Update [Required]
- [ ] [Change the positon of button]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
I change the Position of Continue Button which is present in Customize Avatar View. Using safe area alignment guide.
Fixes #327

power

### Type of Change:

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anubhavpulkit** [comment]
@sunjunkie have a look.

**Comment by sunjunkie** [comment]
This fixes #327 (I made the correction above.)  This looks fine but why do you show the 2nd screen shot (the intro sequence) in the description above?

**Comment by anubhavpulkit** [comment]
I send second screen shot in attachment to show this PR can't change other
pages which is look good without any changes.

**Comment by anubhavpulkit** [comment]
@sunjunkie Can I remove 2nd screenshot if it is not the right way to show in open source?

**Comment by anubhavpulkit** [comment]
@sunjunkie any problem to merge the Pull Request.

**Comment by sunjunkie** [comment]
Yes, remove the 2nd screen shot. I will merge later today.

**Comment by anubhavpulkit** [comment]
@sunjunkie thank you

**Pull request merged**
